kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backup-runner
subjects:
- kind: ServiceAccount
  name: default
  namespace: backup-runner
roleRef:
  kind: ClusterRole
  name: backup-runner
  apiGroup: rbac.authorization.k8s.io